### ISSUE TITLE
Contributing: docs

### ISSUE THREAD

**Issue by guillego** [nerves-hub/nerves_hub_web#1034]
Hey there! I'm starting to use Nerves Hub (just managed to deploy it locally), and I'd be happy to start contributing to the 2.0 docs though I'm a bit lost.

Is there an overview somewhere of what are the biggest differences between 1.0 and 2.0 and some priority order for the docs that need to be rewritten/updated/etc?

I'm going to be deploying it and using it in a semi-production env so I'm happy to start contributing to the docs as I go and figure things out, but it would be suuper great to know where to start contributing more or less!

Thanks for such an amazing project!! 💜

**Comment by jjcarstens** [comment]
Hey @guillego! 👋🏼 The [2.0 announcement](https://elixirforum.com/t/introducing-nerveshub-2-0/55531) has the very high level overview of the goals we're working towards

Apart from that, @oestrich might have some docs/notes he's been keeping on changes and migration/update paths. Most of the changes so far have been greatly simplifying the internal organization for easier deployments

**Comment by joshk** [comment]
I'm closing this issue for the time being.

If you are interested in contributing to NervesHub, you should pop into the `#nerves-hub` and `#nerves-dev` channels in Slack sometime.
