### ISSUE TITLE
import-release-team-keyring not found

### ISSUE THREAD

**Issue by vs-pp** [nerves-hub/nerves_hub_web#1057]
[nerves_hub_web](https://github.com/nerves-hub/nerves_hub_web) Readme and even few other tutorials refer to this script ```~/.asdf/plugins/nodejs/bin/import-release-team-keyring``` to install nodejs

I see that ~/.asdf/plugins/nodejs/ is coming from https://github.com/asdf-vm/asdf-nodejs.git and there is no ```import-release-team-keyring``` in
https://github.com/asdf-vm/asdf-nodejs/tree/master/bin

        ```
        venkat@XPS-8930:~/work/pp/zola/aloha_w2/nerves_hub_web$ git -C ~/.asdf/plugins/nodejs/ remote -v
        origin  https://github.com/asdf-vm/asdf-nodejs.git (fetch)
        origin  https://github.com/asdf-vm/asdf-nodejs.git (push)
        venkat@XPS-8930:~/work/pp/zola/aloha_w2/nerves_hub_web$ git -C ~/.asdf/plugins/nodejs/ branch
        * master
        ```

What would be the procedure to get this script.

**Comment by fhunleth** [comment]
Do you get an error? I think this script may no longer be needed.

**Comment by vs-pp** [comment]
Yes, that script may not be needed as per https://github.com/asdf-vm/asdf-nodejs/issues/325.  I didn't proceed with the rest of the instructions. I will now.

We should probably fix the documentation to remove reference to the script.

**Comment by joshk** [comment]
I'm closing this issue as it is currently stale.
