### ISSUE TITLE
Sentry error when deploying Nerves Hub

### ISSUE THREAD

**Issue by loics2** [nerves-hub/nerves_hub_web#1108]
**Describe the bug**

The deployment script (`./bin/remote deploy`) fails when running the migrations with the following error:

```
ERROR! the application :sentry has a different value set for key :enable_source_code_context during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was not set
  * Runtime value was set to: true

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile sentry --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag


{"init terminating in do_boot",{<<"aborting boot">>,[{'Elixir.Config.Provider',boot,2,[]}]}}
init terminating in do_boot ({,[{Elixir.Config.Provider,boot,2,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

**To Reproduce**

1. Follow the steps describe in the [Self-hosting section](https://github.com/nerves-hub/nerves_hub_web#self-hosting) of the README
2. The 7th step fails

**Expected behavior**

An instance of Nerves Hub should be up and running.

**Additional context**

I tried to recompile the whole project and I tried running `mix deps.compile sentry --force`. Removing `enable_source_code_context: true` in `config/release.exs` fixed the issue.

**Comment by joshk** [comment]
What I suspect is happening (although I haven't tested it locally to confirm) is that you are compiling the code without setting the `MIX_ENV` to `prod` and thus this config is being used: https://github.com/nerves-hub/nerves_hub_web/blob/08b66a5756dbb79867ffa174b02bddb050384a71/config/dev.exs#L102 (the dev config) and then when the app is being started and `release.exs` is used it is resetting up Sentry and the above error is being raised.

But all that said, I've followed the code to see how a release works and it is using docker, and in the dockerfile the `MIX_ENV` is set.

**Comment by joshk** [comment]
could you try removing the `config :sentry` lines in `dev.exs` and `test.exs` and instead add an if block around the sentry config in `release.exs` to only configure sentry if the DSN env var is set?

**Comment by joshk** [comment]
Hi @loics2, just checking in to see if this is still an issue?

I've tried replicating it locally but haven't run into the same issue.

**Comment by loics2** [comment]
Hey, sorry for the delay, I didn't had time to work on that. I can test everything tomorrow.

**Comment by joshk** [comment]
I've made a bunch of improvements on the `main` branch, you might want to pull the most recent version.

**Comment by loics2** [comment]
Well, I guess this issue is not relevant anymore, since the deployment scripts have been removed in #1130 and everything runs fine on my local environment.
