### ISSUE TITLE
host nerves-hub and link my firmware step-by-step?

### ISSUE THREAD

**Issue by gabrielmancini** [nerves-hub/nerves_hub_web#1228]
Hello everyone,
there is some walk throw for this integration, i am feeling lost about the certs process...
kind of sequence of articles/issues/forum posts, like "put nerves-hub in production and link your first firmware for OTA step-by-step"?
i open an issue on https://github.com/nerves-hub/nerves_hub_link/issues/156 to clarify my point

**Comment by joshk** [comment]
Hi @gabrielmancini 

Thanks for opening this issues.

We are in the process of updating our docs, which will include a much simplified way to setup NervesHub.

I'm going to close this issue for the time being.
