### ISSUE TITLE
No way to register a brand new account

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#1252]
**Describe the bug**
when you deploy nerves-hub, there is no way to create a user

**To Reproduce**
deploy nerves-hub on a fresh setup

**Expected behavior**
create a user

**Screenshots**
![image](https://github.com/nerves-hub/nerves_hub_web/assets/21150830/71478d09-48a8-4f52-b9fa-4938cef6732c)

**Comment by joshk** [comment]
I think this is expected behaviour.

I believe the best path forward would be to add a script or mix task that would create an account. All other accounts should be invited to the instance (or use that script).
