### ISSUE TITLE
Create account link in invite email is broken

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-hub/nerves_hub_web#132]
The link that is in the invite email to click to create an account is broken. Here is an example
```
x-webdoc://39337357-8A37-4CC0-8DDD-060D24F9CE48/://www.nerves-hub.org/invite/e47c7c07-d00c-4e3d-ad59-df9232d637a7
```
This may just be a configuration of prod. It seems to work properly when sending email from localhost.

**Comment by jlmcgehee21** [comment]
@mobileoverlord did this get fixed?

**Comment by mobileoverlord** [comment]
nope. easy one to pick up

**Comment by ConnorRigby** [comment]
Dug into this a little bitk:

error is here:
https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_www/lib/nerves_hub_www_web/templates/email/invite.html.eex#L5
https://github.com/nerves-hub/nerves_hub_web/blob/cec204aebccda27832a6e6d12ffb1c07e6a6cf89/apps/nerves_hub_www/lib/nerves_hub_www_web/views/email_view.ex#L5
