### ISSUE TITLE
Error when rescinding already accepted invites

### ISSUE THREAD

**Issue by beltranaceves** [nerves-hub/nerves_hub_web#1353]
**Describe the bug**
When rescinding an org invite that has already been accepted, an error occurs
`FunctionClauseError at DELETE /org/nerveshub/settings/invite/`

**To Reproduce**
1. Go to '/org/<org_name>/settings/users'
2. Click on 'Add new  user'
3. Create and send user invite
4. Go back to '/org/<org_name>/settings/users'
5. Open anonymous tab and accept invite
6. Back on the original tab, without refreshing the page in '/org/<org_name>/settings/users', click on 'Rescing' 

**Expected behavior**
A small error popup shows up saying the user has already accepted the invite and the 'Rescind' button disappears

![image](https://github.com/nerves-hub/nerves_hub_web/assets/22192199/ac90a331-3759-4591-a9fd-75c1cf770d4d)

**Comment by joshk** [comment]
Thanks for the report.

I've just pushed a PR for review which fixes this.
