### ISSUE TITLE
Feature Request: Migrate Runtime Docker image to Alpine (or similar) from Ubuntu

### ISSUE THREAD

**Issue by rraub** [nerves-hub/nerves_hub_web#1427]
**Describe the Feature**
The Ubuntu image contains a lot of bloat and ends up being over 200MB, which increases costs and startup times. This bloat also comes with many security findings that we could omit with a smaller base image. I'm not saying Alpine is the perfect choice here, but we should be able to shrink the runtime image by over half by moving to a smaller base image. 

I'm also totally open to other base images. Alpine isn't always the best choice, but it's a good common one to start with.  

(also sorry about blowing away most of the template for this feature request; I only had a bug request template to choose from)

**Comment by fhunleth** [comment]
It used to be Debian. I know Alpine is smaller, but Debian might be a quick step in the right direction?

@joshk You switched from Debian to Ubuntu in 74e410e75. Do you remember why?

**Comment by joshk** [comment]
Hi Ryan

Nothing to apologize for, the issue bug template isn't suited for this sort of discussion.

I can't remember the reason I switched to Ubuntu, and I'm more than happy to look into other options.

Looking at Ubuntu vs Debian vs Alpine

[Ubuntu Noble](https://hub.docker.com/layers/hexpm/elixir/1.17.1-erlang-27.0-ubuntu-noble-20240605/images/sha256-f1e40a82ed5d3547f4a1c17fe958cb6113561c465a4a4adbc627714839cd39c2?context=explore) : 76MB
[Debian Bullseye](https://hub.docker.com/layers/hexpm/elixir/1.17.1-erlang-27.0-debian-bullseye-20240701-slim/images/sha256-33cfae7f0e2a46385c1afdea8c03b0b8dcaf22f9440b6f59d29d57d9b0766953?context=explore) : 77MB
[Alpine 3.20](https://hub.docker.com/layers/hexpm/elixir/1.17.1-erlang-27.0-alpine-3.20.1/images/sha256-ebf0b049466fe45cc15a9942eb963f2679a82bf4888c096ab95661c5e67215bd?context=explore) : 44MB

If we want to have a smaller image we would need to look into Alpine.

Regarding your points around increased costs, startup times, and security issues, are there some numbers or references we can put behind those? For example, if we are to change the base image it would be useful to point to a tangible benefit the switch has provided.

**Comment by rraub** [comment]
I didn't realize the image sizes had grown to be so similar for the prebuilt erlang/elixir images that you referenced! 30mb difference isn't that huge. However, I'm more focused on the resulting [runtime image](https://github.com/nerves-hub/nerves_hub_web/blob/main/Dockerfile#L7) which starts off as: 
* https://hub.docker.com/layers/library/ubuntu/noble-20240605/images/sha256-3963c438d67a34318a3672faa6debd1dfff48e5d52de54305988b932c61514ca?context=explore (28mb)
* https://hub.docker.com/layers/library/alpine/3.20.2/images/sha256-eddacbc7e24bf8799a4ed3cdcfa50d4b88a323695ad80f317b6629883b2c2a78?context=explore  (3mb) 

Obviously the final built image contains quite a bit more (hard to compare apples to apples without a working alpine build). But the main goal is just reducing the image down to the essentials to reduce the security surface area and save on bandwidth while also enjoying faster startup times.

Cost impacts are going be quite low, for example AWS ECR Storage is $0.10 per GB / month, However if you don't have a optimal setup (using a public network) you could incur egress data transfer fees of $0.09 per GB ([reference](https://aws.amazon.com/ecr/pricing/)).  This isn't as big of a factor, but sometimes these small costs add up when image caching isn't working in your favor and every container that scales up/down incurs this data transfer. 

Additionally @fhunleth pointed me towards a few [noticeable performance regressions](https://elixirforum.com/t/using-alpine-and-musl-instead-of-gnu-libc-affect-performance/57670) with `musl` (alpine) vs `libc` (ubuntu) this would out weight any image size advantages.

**Comment by joshk** [comment]
@rraub I totally agree with you that we should prioritize a reduced security surface. 

Would you have some time or opportunity to try putting together a PR which uses Alpine instead?

**Comment by joshk** [comment]
@rraub would you like me to keep this issue open?

**Comment by rraub** [comment]
Unfortunately, I've not got the time to put together a PR, and as we've discussed, the potential isn't as clear or as large as we initially thought. So yes, we can close this issue for now and perhaps revisit it later if need be. Thank you @joshk !
