### ISSUE TITLE
Make it possible to delete user certificates

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-hub/nerves_hub_web#144]
The UI has a button for delete and deactivate. I think that we should remove deactivate and wire up the delete button with a confirmation modal.

**Comment by jlmcgehee21** [comment]
@mobileoverlord where are the user certificates in the UI?

**Comment by mobileoverlord** [comment]
`/account/certificates`

**Comment by jlmcgehee21** [comment]
:+1: was just seeing that in the router.  Can a user only access their own certificates?  If so, should we add a link to `/account/certificates` on the account settings page?

**Comment by mobileoverlord** [comment]
A user should only be able to access their own certificates, we can add a lnk

**Comment by jlmcgehee21** [comment]
Closing -- was addressed by: https://github.com/nerves-hub/nerves_hub_web/pull/163
