### ISSUE TITLE
`ssl_opts` deprecated and db server certificate not being verified

### ISSUE THREAD

**Issue by magreenbaum** [nerves-hub/nerves_hub_web#1445]
**Describe the bug**
After `postgrex` was [upgraded to 0.18.0](https://github.com/nerves-hub/nerves_hub_web/pull/1305), `ssl_opts` was deprecated in favor of `ssl` and `ssl` set to true does not verify server certificate. If previously `verify_peer` was configured in `ssl_opts`, we're now getting warnings:
```
setting ssl: true on your database connection offers only limited protection, as the server's certificate is not verified. Set "ssl: [cacertfile: path/to/file]" instead
```
Refs:
https://hexdocs.pm/postgrex/changelog.html#v0-18-0-2024-05-18

**To Reproduce**
1. Pass in `DATABASE_PEM` to verify db server cert
2. See warnings in logs on startup 

**Expected behavior**
Verify database server certificate. No warnings.  

**Additional context**
https://github.com/nerves-hub/nerves_hub_web/blob/5e6b3370e158e83a418e2530115e137971a23542/config/runtime.exs#L205-L222

**Comment by joshk** [comment]
Thanks for reporting this @magreenbaum 

Looks like @oestrich has whipped up a PR to address this issue. We should have it merged in soon :)
