### ISSUE TITLE
Device selections remain even when filter filters the selected devices out

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#1475]
**Describe the bug**
Devices can remain selected when changing the filter and that makes it easy to accidentally apply a bulk action to a hidden device.

**To Reproduce**

1. Go to the devices page and select a few devices
2. Update the filter so that those devices won't show
3. See that the selected device count next to the "Bulk actions" text stays the same
4. Now select a few more devices

**Expected behavior**
I'm not sure how other UIs handle this issue, but I found this surprising when I first noticed it. I was enabling firmware updates at the time so this was harmless, but I didn't realize until pretty late in the process that I was re-enabling firmware updates on devices that I had selected a long time ago.

**Comment by joshk** [comment]
Ahhhh, this is due to a funky way the device selection works. 

We store the selected devices in the LiveView, as they are added. If we switched to using a more form based approach, then this wouldn't be an issue. 

I think the quick fix is to wipe all selected devices when the filters are changed.

**Comment by nshoes** [comment]
@joshk this looks fixed, could you sanity-check me?

![CleanShot 2024-10-31 at 10 55 27](https://github.com/user-attachments/assets/a246b79a-cc47-47f2-8528-2c7926fe38a4)

**Comment by joshk** [comment]
Looking at the commits, I think Lars fixed this 3 months ago, so yes, you are on the money that this issue can be closed.

Thanks Nate!
