### ISSUE TITLE
Feature: Make world map work at scale

### ISSUE THREAD

**Issue by lawik** [nerves-hub/nerves_hub_web#1480]
Assume 500.000 devices :)

- Show many devices in one area in a sensible way
- Show only part of map with devices
- Change device connectivity subscription scheme
- Re-enable zooming on the map and re-calculate device display

**Comment by elliotjon** [comment]
I can't take it :)

**Comment by lawik** [comment]
The cluster map is pretty close to this. It gets slow to load around 100K devices and that is a limit of the mapping system seemingly.

This iteration of it is done.
