### ISSUE TITLE
Selecting a product in bulk move clears the dropdown

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#1526]
Sometimes when you select a device and then choose an org/product to move it to, the dropdown clears after selection.

I believe submitting may still work, but it looks confusing to the user at times

/cc @tylerfloyd

https://github.com/user-attachments/assets/e78586a4-ce55-4d02-8ab1-42162cc8eb9f

**Comment by nshoes** [comment]
Looks like this was solved with the associated PR, closing this out.
