### ISSUE TITLE
Downloading the certificate for a device goes to an error screen

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#1532]
1. Go to a device's settings
2. Click on '...'
3. Click download

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/6ac8cbc5-b121-4b1a-82ae-662197b806b7">

If this seems to work, then it might be because this device was moved from one org to a different one.

**Comment by nshoes** [comment]
This looks like it was fixed in the associated PR, closing this issue.
