### ISSUE TITLE
Track device connections

### ISSUE THREAD

**Issue by joshk** [nerves-hub/nerves_hub_web#1547]
The recent additions of `connection_status` to Devices, along with a Device heartbeat so we know that the device is still online, is a great first step.

For us to support graphs that show device connection history, and graphs and stats on a product level, we ideally need to track device connection history. This will also enable us to detect devices which have flapping connections and need some attention.

The suggestion would be to add a new schema, `DeviceConnection`, which includes:
- `device_id` (int)
- `established_at` (date and time)
- `last_seen_at` (date and time)
- `disconnected_at` (date and time)
- `disconnected_reason` (text) (future enhancement)
- `metadata` (jsonb)

Changes to `DeviceSocket` and the `Devices` context will be needed.

And an index on `device_id` and `establisted_at` should be a good start, possibly a second index on `device_id` and `disconnected_at`.

I'm wondering if we add a `status` field which is essentially a cache of the connection status, eg. `connected` or `disconnected`, but we can also figure this out based on `establisted_at` and `disconnected_at` having values or not.

**Comment by oestrich** [comment]
Some of this _was_ tracked in AuditLogs, but it was so verbose that it blew away anything actually important most of the time. So this seems like a good change. The audit logs for this switched to plain old info logs, but that's not very easy to determine connection length.

In regards to a `status` field, I think whatever is easiest to determine a green dot and filtering by connection status is good. Which seems like a cached field would be easiest on the database so we don't have to do a join?

**Comment by joshk** [comment]
Yeah, I saw we used to add an audit log for a connection. The AuditLog schema isn't good for tracking information like this.

I agree with you re `status`. @elinol is working on this feature at the moment and raised the same question. We agreed it would be good to have for easy searching.

Sorry, what do you mean by `so we don't have to do a join`? Do you mean we should also store `status` on Device so we don't need to do a join?

**Comment by oestrich** [comment]
Oh, yeah, I read that as `devices.status` not `device_connections.status`. But whatever makes things quick is fine with me. We have a good number of flapping devices (thanks LTE) so this table will likely fill up quickly haha

**Comment by elinol** [comment]
Here's a draft where we can discuss this further if you like: https://github.com/nerves-hub/nerves_hub_web/pull/1572
