### ISSUE TITLE
New awesome charts can't handle negative numbers 📉 

### ISSUE THREAD

**Issue by lawik** [nerves-hub/nerves_hub_web#1566]
My new sine-wave metric doesn't look very good because it dips below 0.0.

Code to add it to a device:

```
defmodule Foo, do: def swoosh, do: :math.sin(System.system_time(:second))
conf = Application.get_env(:nerves_hub_health, :metrics)
conf = Map.put(conf, :swoosh, {Foo, :swoosh, []})
Application.put_env(:nerves_hub_health, :metrics)
```

Screenshot:
<img width="1186" alt="Screenshot 2024-09-27 at 21 08 47" src="https://github.com/user-attachments/assets/c19007b8-8ee4-43d0-b2d4-c9d910fdbce9">

I think this might be a job for @elinol ✨

**Comment by elinol** [comment]
https://github.com/nerves-hub/nerves_hub_web/pull/1580
