### ISSUE TITLE
Device unable to connect to NervesHub

### ISSUE THREAD

**Issue by BryanLeong** [nerves-hub/nerves_hub_web#1569]
**Describe the bug**

Devices using shared secret auth are not able to connect to NervesHub from 1fba01e onwards (tagged docker image, probably not the exact commit).

The last version where devices are able to connect is bd1847c.

**To Reproduce**
1. Set up shared secret auth
2. Deploy NervesHub [1fba01e](https://github.com/nerves-hub/nerves_hub_web/pkgs/container/nerves-hub/275988820?tag=1fba01e)

**Expected behavior**

Devices connecting with shared secret auth should be able to connect and come online.

**Screenshots**

In the web interface, "seen" keeps getting updated to "now", but the device never comes online:
![image](https://github.com/user-attachments/assets/52a46b15-f59c-44a3-8510-ff3294ae7973)

The device is stuck in a cycle trying to join the channel but getting an error after:
![image](https://github.com/user-attachments/assets/221b2ffb-d8e2-42b9-9d88-eb275c319b93)

Last working version for me (bd1847c):
![image](https://github.com/user-attachments/assets/f5e48017-9f3d-4ebe-927e-52c8e88fa8d8)

**Additional context**

- NervesHub 1fba01e deployed on AWS ECS with an Application Load Balancer handling SSL termination.
- RPi4 device running `nerves_hub_link` `2.5.1` connects via shared secret auth

**Comment by BryanLeong** [comment]
Oops, nevermind. Just tried the latest tagged release and the issue seems to have been fixed 😅

**Comment by joshk** [comment]
Thanks for creating this detailed issue. 

Funnily enough we discovered this issue yesterday and fixed it with https://github.com/nerves-hub/nerves_hub_web/commit/c19a63528769a89c2933e0422583e5bfbe421428

Sorry for the issues you ran into.

As a side question, would you be interested in trying out NervesCloud? (hosted NervesHub)

**Comment by BryanLeong** [comment]
Would have been interested a few weeks back when I was still setting up infra, but I think I've got it sorted now.

Appreciate the offer though 😄
