### ISSUE TITLE
Devices in `penalty box` take up concurrent slot of deployments

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#1617]
We have deployments which targets several hundred devices. In some cases, it takes hours or days to get through updating devices. While investigating, it was noted that several devices in flight were actually now in the penalty box but were still being counted in the deployment orchestrators concurrent limit. So the effect in our case was that only 1 or 2 devices were being updated at a time

**Comment by joshk** [comment]
ohhhhhhh, interesting.

I believe we need to add a `Devices.clear_inflight_update(device)` in `Devices.verify_update_eligibility` so we can track that the device isn't updating, which will fix the updating count used by the orchestrator.
