### ISSUE TITLE
Don't send a firmware update down if it failed the previous time

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#202]
I had an update that failed to install. After each reboot, it would attempt the update again. That actually complicated debugging the issue. I think that the desired behavior would be to put the device into timeout and not attempt to update until an administrator intervenes. This issue is only for updates that get an error code from fwup. Updates that fail due to network issues can continue to retry like they do now.

**Comment by jlmcgehee21** [comment]
@fhunleth, how can we know that this type of failure occurred? Does the client need to report it before we can take action?

**Comment by fhunleth** [comment]
Right - the client will need to report the error. The current `nerves_hub` project doesn't do a good job of this yet.

**Comment by fhunleth** [comment]
Upon more thought, I think we should do two things that don't require cooperation from the device:

1. Rate limit updates to devices to put an upper bound on how often devices get notified of updates. The limit could be one update notification a minute. That would prevent a situation I just saw where the client crashed during the update, restarted, and got told to update again, etc. It reconnected with the server pretty aggressively.
2. Only let the device request an update from the same UUID n times before marking it failed. For example, if a device is running firmware A and is told to update to B, if it reports in that it's running firmware A more than n times after being told to update to B, then NervesHub raises an alarm and stops trying to update the device.

**Comment by jjcarstens** [comment]
This was introduced with threshold and rate limits on a deployment
