### ISSUE TITLE
Clicking NervesHub icon looks like it logs you out

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#204]
Click on the icon in the upper left:

![image](https://user-images.githubusercontent.com/64669/44275100-e5e60180-a211-11e8-8435-c06103cee647.png)

The next screen is https://nerves-hub.org/ and it looks like you've logged out. It would be nicer if it took you to the dashboard when you're logged in.

**Comment by stwf** [comment]
semi addressed in PR:
https://github.com/nerves-hub/nerves_hub_web/pull/214

Front page now reflects logged in status at least. and a link to the dashboard was added in the header.

**Comment by stwf** [comment]
I do have an alternate solution (I feel like the logo click should always take you home). So on the front page we can check to see if the user is logged in, and if they are disply the logged in header, so it would be more clear they are still logged in.

Either way is fine though, let me know.
