### ISSUE TITLE
Update spacing/text on the product listing page

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#205]
Here's the current view:

![image](https://user-images.githubusercontent.com/64669/44275345-7cb2be00-a212-11e8-995c-9611202ed3ee.png)

At a minimum, it would be nice to improve its looks.

In my usage, I almost always go to "show" so that I can click on "view firmware" or "view devices". Having those buttons available on this screen would be useful.

I'm also for removing the edit button for now. Changing the product name is dangerous since it has to match the metadata in .fw files. Maybe in the future, we'll have more useful things to edit on the product.

**Comment by jlmcgehee21** [comment]
@stwf I also noticed that the footer does not always fall below content, so that could be addressed here too.

**Comment by stwf** [comment]
I also think the delete button is pretty dangerous too. I know its needed, and I will leave it in for now, I'm just not sure the JS alert is enough, maybe something like Github does where you need to retype the Product name first?

**Comment by stwf** [comment]
addressed in PR:
https://github.com/nerves-hub/nerves_hub_web/pull/233

**Comment by jlmcgehee21** [comment]
above PR was merged
