### ISSUE TITLE
Add a button to get to deployments

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#206]
The current way to get to them is to manually go to https://www.nerves-hub.org/products/<product_id>/deployments. Here's an example:

![image](https://user-images.githubusercontent.com/64669/44275681-6a854f80-a213-11e8-984e-1b49a668683b.png)

I think this is another button next to the product on the product listing page. It probably should also be on the product "show" page.

**Comment by jlmcgehee21** [comment]
They can now be accessed via the products index/show pages
