### ISSUE TITLE
Make an initial pass at a dashboard

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#210]
The current dashboard looks like:

![image](https://user-images.githubusercontent.com/64669/44276953-2431ef80-a217-11e8-8f1b-e5ffb52ed42d.png)

However, I already have a product and device, so it would be nice to see something else besides the "to get started" help. I don't have an easy-to-implement suggestion for the very near-term. Long term, I'd like metrics and log information for what's been happening. It might be sufficient to just remove the "To get started, add a product..." text and button if products already exist.

**Comment by stwf** [comment]
First pass addressed in PR:
https://github.com/nerves-hub/nerves_hub_web/pull/214

**Comment by jjcarstens** [comment]
Resolved with the new UI update. More specific dashboard details should have a new issue
