### ISSUE TITLE
Limit number of firmware per product per org

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-hub/nerves_hub_web#216]
We should limit the number of firmware that is stored per product to prevent storage from growing out of control. The limits should be able to be set for each org. As par of this, should enable a mechanism for auto-pruning older versions of firmware.

Depends on https://github.com/nerves-hub/nerves_hub_web/issues/195

**Comment by jlmcgehee21** [comment]
https://github.com/nerves-hub/nerves_hub_web/pull/245
