### ISSUE TITLE
Back button on `New Org` screen goes to invalid route

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-hub/nerves_hub_web#235]
**Describe the bug**

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'org dropdown -> new org'
3. Click 'back'

**Expected behavior**
The page should navigate somewhere, probably the dashboard?

**Comment by jlmcgehee21** [comment]
This definitely is beyond my capabilities, but it might be nice to have some frontend test suite that checks for bad routes, etc.
