### ISSUE TITLE
Device's client certificate revocation

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#250]
Prevent a device from connecting at the SSL layer by revoking its certificate and maintaining a CRL list for incoming SSL connection.

The goal is to prevent misbehaving devices from being able to interact with Nerves Hub as soon as possible.

**Comment by squaresurf** [comment]
Where should the CRL list be stored?

How will certs be added / removed from the CRL?

**Comment by fhunleth** [comment]
I think this can safely be closed since NervesHub stores the device certificate for every device. The only operation that requires PKI is the auto-registration mechanism. I think that we could severely rate limit auto-registrations if we're worried about a DoS from devices that would have been excluded by a CRL.
