### ISSUE TITLE
Firmware Zombies

### ISSUE THREAD

**Issue by jlmcgehee21** [nerves-hub/nerves_hub_web#258]
Firmware files are persisted to the file store _before_ the record is added to the database.  If we don't have a transactional guarantee and rollback strategy in place, a failed DB insert will yield a zombie firmware file.

`prepare_firmware_params` (https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_core/lib/nerves_hub_core/firmwares.ex#L72) is called in the controllers _before_ `create_firmware`.

**Comment by jlmcgehee21** [comment]
Also noticed that `Firmwares.delete_firmware/1` deletes the firmware from the file store before deleting the firmware record from the database.  This means that anytime a delete fails due to database constraints, we will have a firmware record in the DB which points to a non-existing firmware file.

**Comment by jlmcgehee21** [comment]
@danielspofford -- You making headway here?

**Comment by danielspofford** [comment]
@jlmcgehee21  Yep. I have had the create and delete scenarios done already for a couple days and tests in place. I just am not super happy with how I had to go about testing. Gonna take another look here shortly and submit a PR today.
