### ISSUE TITLE
Improve speed at which a device's status is considered offline

### ISSUE THREAD

**Issue by danielspofford** [nerves-hub/nerves_hub_web#265]
> I just tested this locally and its working. We may want to trim down the timeout times from either the socket disconnecting, or the presence sync. It appears online much faster then it will appear offline. I had to power the unit down and wait because it didn't seem to timeout faster then it took the device to reboot. Which isn't a terrible problem to have, but, we can do better :). Lets tackle this in another issue.

https://github.com/nerves-hub/nerves_hub_web/pull/261#issuecomment-422152003

**Comment by jjcarstens** [comment]
I think this may be resolved? I'm seeing almost immediate reports of device going offline via the Presence tracking. In fact, it takes a little bit longer to show online.

I haven't quite been able to reproduce this

**Comment by jjcarstens** [comment]
There have been several improvements around device presence and channel connection. I don't think this issue is valid any longer
