### ISSUE TITLE
Postgres deadlock on tests

### ISSUE THREAD

**Issue by jlmcgehee21** [nerves-hub/nerves_hub_web#270]
Intermittently, the async tests fail due to a Postgres deadlock.  Changing the fixtures to operate as shown in the [Ecto docs](https://hexdocs.pm/ecto/Ecto.Adapters.SQL.Sandbox.html#module-database-locks-and-deadlocks) should solve this problem.

**Comment by jjcarstens** [comment]
I _believe_ this is resolved. I haven't run into any deadlock issues running the specs and [`Fixtures` implements a counter](https://github.com/nerves-hub/nerves_hub_web/blob/master/test/support/fixtures.ex#L319-L321) now (which is what I think was attempting to be linked in the out of date ecto doc?)

Can you confirm @jlmcgehee21 ?

**Comment by mobileoverlord** [comment]
This is believed to be resolved
