### ISSUE TITLE
User roles within an org

### ISSUE THREAD

**Issue by jlmcgehee21** [nerves-hub/nerves_hub_web#271]
`owner`, `admin`, etc.

We need to think about how this should work from a user's perspective, then understand how it should be implemented from a DB schema perspective.

**Comment by mobileoverlord** [comment]
I was interested in this from the perspective of being able to give users super access to an additional tool that is used for navigating all accounts / data in the nerves hub installation. What are the current common practices when it comes to permissions / roles and phoenix?

**Comment by danielspofford** [comment]
https://github.com/cpjk/canary is a good choice for facilitating authorizations and ensuring you do them in a consistent manner. It leaves the decision of what data dictates authorizations up to the user: you could decide to create rules like if the `user_id` is `1` then they can do _something_, but you could also make users `has_many` "tags", and then when evaluating rules look at the tags on a user and authorize based on that.

If all you want is rigid RBAC where users can only hold 1 role at a time, then just add a `role` column to users.

The former is very future proof but a little bit more work, the latter is a little easier to implement but may leave you wishing for more in the short term and could potentially lead to a refactor down the road when more fine grained control is required.

**Comment by mobileoverlord** [comment]
This is in master  and available to manage via `nerves_hub_cli` >= 0.5.0
