### ISSUE TITLE
Device status

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#31]
It's useful to know a high level status of the device (like red, yellow, green or failed, warnings, ok). The idea is that once you get enough devices, it's convenient to be able to see at a glance what's happening rather than clicking through to a device detail view. 

It seems difficult to combine all interesting device status into one field, so here's a high level idea that has two columns:

* Overall status
  * Red/failed -> offline for > 1 day
  * Yellow/warning -> connected in the past day; an error has been submitted
  * Green/ok -> connected in the past day; no error logs

* Firmware update status
  * Red/failed -> firmware update needed, but errors or retries detected
  * Yellow/warning -> firmware out-of-date. An update will be requested on next connect
  * Green/ok - firmware up-to-date

The firmware update status field would replace the "update pending" column

**Comment by jlmcgehee21** [comment]
@fhunleth, since we're using channels, what about using presence here?

**Comment by fhunleth** [comment]
Yeah, I had been thinking that a while ago, but I haven't thought about it recently.

**Comment by mobileoverlord** [comment]
I am absolutely on board using Presence. Production already supports it. The api, device, and www servers are already clustered.

**Comment by jlmcgehee21** [comment]
Yeah, we used in on our firmware update server. I wasn't on the project during the time we did it, but it seemed to work super well.  Of course we'll have to track a bit more info to have `red, yellow, green` based on the above definitions, but I think Presence can be at the heart of it.

I'd like this to be my next major task after I get a few of these cleanup type issues out of the way.

**Comment by jjcarstens** [comment]
We have lots of statuses now. New issues for more fine tuned changes if desired
