### ISSUE TITLE
CI / API User

### ISSUE THREAD

**Issue by danielspofford** [nerves-hub/nerves_hub_web#315]
Right now you can use the local keys from a user to authenticate within CI or whatever. It is unfortunate that you either have to use _your_ keys, or go through the process of registering a user with an email, a website password, etc. just to use the local keys.

It would be nice if I could generate a CI / API "user" specific to an org that didn't require anything else like email, but provided me with a key and cert.

Note that by using _your_ user's cert and key that you are forced to give the CI more access than you might want (to other orgs for example).

**Comment by ConnorRigby** [comment]
This is related to #317 i think. I was just planning on making a dummy email and stuff, but having an actual CI "User" is a valid option also.,

**Comment by mobileoverlord** [comment]
I think I like the simplicity of using the User certificate infrastructure to grant access to servers, especially with the addition of roles on products and orgs. To make it easier to generate the user certificates, we might want to add the ability to create a User cert from the web site. This was brought up in #435
