### ISSUE TITLE
Invitations should lookup an existing account or register one

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#317]
**Describe the bug**
Accepting an invite prompts a user to make an account. If you are being added to a second 
org, you already have an account and just need to sign in to accept the invite.

**To Reproduce**
1) Create account
2) Create 2 orgs
3) Invite second user to join org 1
4) Create second account
5) invite second user to join org 2
6) ???
7) Profit

**Expected behavior**
Expected to be able to login if my email is already associated with an Account. 

**Additional context**
This is important for having multiple users with a `staging` and `production` environment.

`admin@some.org` - Root account
`deploy@some.org` - CI account so certs can be revoked if it gets pwnd

`deploy` needs to be part of the same nerves-hub orgs as `admin`

**Comment by jjcarstens** [comment]
I think it would be nice to have a "notifications" part of the nerves hub UI where an existing user could see this request and just accept there once logged in. But I think that's a much bigger cut.

For now, going to just adjust this to find or create the user and function from there (unless there are any objections)
