### ISSUE TITLE
Device interaction log

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#32]
It would be nice if the server could maintain an interaction history with each device. This doesn't have to be fancy. It could just contain things like "device connected at time x", "firmware update requested", "device's firmware version is now y". The idea is to have historical information about a device if a bug report is incomplete or there's an issue with firmware updates reverting.

**Comment by jjcarstens** [comment]
This is partially started with introduction of `AuditLogs`. Though, will probably be a continuing effort to further define what history we need to store and how/where to display it
