### ISSUE TITLE
Allow a device to have a "fallback" firmware

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#320]
I had all intentions of implementing this today, but ran out of time.
Related to: #319 

If a device connects with an unknown firmware, it should have the ability to apply a known good firmware.

I've tried this a few ways to no avail so far:

* adding a `fallback_firwmare_id` to `Device`
* adding a `default` Deployment per `product`

I didn't like either of them but am willing to revisit if someone else likes those ideas.
I think this feature would also easily lead into forcing a device onto a particular firmware which i also tried to implement naively. the `Deployment` association gets in the way here a bit.

**Comment by ConnorRigby** [comment]
I like this idea to some extent. I thought of doing it this way also. As far as i know we don't use any connect/join params in the client. It could be added there. Seems a little strange to implement it this way, but i can't exactly pin point _why_

**Comment by jlmcgehee21** [comment]
The concern might be a "cold start" issue, where you don't know a valid fallback firmware uuid to bake into the firmware at the time of building it.

However, this problem still exists from the opposite side.  If a device connects with an unknown firmware, how can we safely decide what it should fall back to in NervesHub. If the firmware is unknown to NervesHub, how can NervesHub make that decision?

This complexity is why we initially built it to only work with no firmware versions. I know that's sidestepping some real-world issues, but the solution is tricky, especially if you were to have _many_ devices come online with unknown firmwares.  You would have no guarantees regarding which firmwares these devices could accept (or fall back to), which would make moving them all onto a known version a potentially nightmarish endeavor.

**Comment by mobileoverlord** [comment]
@fhunleth and I had an offline conversation about this. Here is my understanding of the result of that conversation.

There are a few issues that are related, here are the issues that we identified:
* Allowing the update of
  * Connecting with unknown firmware and determining deployment eligibility.  
  * Connecting with firmware that has been garbage collected. This would be a symptom of plugging in a device thats been in the closet and offline for a long period of time. 
* Preventing the update of:
  * Connecting with firmware that has the same semantic version but a different uuid. This scenario is more typical when trying to debug a pipeline issue or test devices.
  * Connecting with firmware that was updated out of band to a higher version.

This is the strategy we came up with

* Unknown firmware will supply additional metadata to the server either through connect params or an after join request. 
* The supplied product metadata can be used to find deployments for that org for that product.
* The supplied version metadata is then used in a requirement match of `supplied_version < deployment_firmware_version`. 
* Deployments will be updated to require the `version requirement` field. This field will default to `supplied_version < deployment_firmware_version`.

**Comment by jlmcgehee21** [comment]
I like that @mobileoverlord -- seems pretty similar to my suggestion (minus the explicit fallback pointer). So essentially, it will be the responsibility of whomever compiles the firmware to include identifying information that will either render it eligible or ineligible for updates?

**Comment by mobileoverlord** [comment]
The supplied firmware metadata is the same information that we use for constructing the firmware record when it is initially uploaded. So, it would be a fall back to loose linkage. We would have enough information to construct a query to return all deployment records that have firmware for the supplied product ordered by modified descending. This result should be fairly small. We would then walk the list to find first match of `supplied_version < deployment_firmware_version`. This way, nothing extra needs to be thought of or baked in.

**Comment by jlmcgehee21** [comment]
@mobileoverlord -- in the solution you laid out, is the intent to push the "valid" firmware to the device if it exists?

**Comment by mobileoverlord** [comment]
To implement, I think its a matter of requiring that all deployments default to a version requirement of `device_firmware_version < deployment_firmware_version`. We will likely have to alter the routine that checks for eligible deployments to allow passing product, firmware version, and tags instead of a whole firmware struct.

**Comment by jlmcgehee21** [comment]
Right, but assuming that there _is_ a firmware that matches the "fallback" loose linkage, are we requiring that the device updates to it immediately?  Or are we just only using that as a stipulation for receiving an update at some point in the future?

I hope that makes sense.

**Comment by mobileoverlord** [comment]
I think that if you show up with unknown firmware, and there is an eligible deployment, we respond with a message that an update is available immediately.

**Comment by ConnorRigby** [comment]
I agree. Users may implement a `NervesHub.Client` to reschedule an update

**Comment by jjcarstens** [comment]
Whats the current state of this? It seems to be _mostly_ implemented except that getting eligible deployments is scoped to a product. So if the device has unknown firmware which does not have the same `product` in its meta, then it would not be told to update to any firmware. Maybe this is expected?

A lot of work has been done since this, so might be worth revisiting to further outline what needs to happen (or break into a new issue)

**Comment by ConnorRigby** [comment]
i think it's not as much of an implementation detail, but an "intended behavior" detail. 

In some cases i could see it being weird that if you booted up a test device and it automatically updated itself. 

A different use case however (the one i originally wanted this feature for) is to tty a firmware with devices connected to it. So if i had a device that has been offline forr 6 months, i don't want that single device to prevent my firmware from being TTL'd. I would just want it to update to whatever the latest available is.
