### ISSUE TITLE
`NervesHub.update()` behaves unexpectedly with a never-seen-before-device

### ISSUE THREAD

**Issue by danielspofford** [nerves-hub/nerves_hub_web#322]
I think it is because

https://github.com/nerves-hub/nerves_hub_web/blob/8b09a433ede2f6cc7bb1417bb2c5814b96f448c4/apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex#L16

sets the last known firmware whereas

https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_device/lib/nerves_hub_device_web/plugs/device.ex#L10

does not. And

https://github.com/nerves-hub/nerves_hub_web/blob/8b09a433ede2f6cc7bb1417bb2c5814b96f448c4/apps/nerves_hub_web_core/lib/nerves_hub_web_core/devices.ex#L82

returns `[]` if there is no last known firmware.

**Comment by danielspofford** [comment]
When a device calls `NervesHub.update/0` I don't think it sends its fw uuid. This is problematic for the reasons outlined above, it basically means that you can not resolve a valid new firmware.

I think we should facilitate this, does anyone care how this happens? I think we could send a header / query string param with the uuid in it. Thoughts?

**Comment by ConnorRigby** [comment]
I don't think the name is particularly important as long as we pick something uniform. 

i think `X-NervesHub-<field>` would be a good prefix.

* `X-NervesHub-Dn` - As described in that issue
* `X-NervesHub-Uuid` - As described here

are two headers i think would be useful.
