### ISSUE TITLE
Guard against accidental device delete and disable

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#33]
The device delete and disable buttons are on the main device listing screen at the moment. This is fine for now, but it would be nice to move them to either a device detail screen or have a sequence of "are you sure" screens. The idea is to prevent an accidental delete or disable since those should be rare operations in production and they have big consequences to devices.

**Comment by jlmcgehee21** [comment]
@fhunleth, we have a js alert that comes up when you click delete. Will this satisfy the needs of this issue enough to close it, or should we keep it open?

**Comment by fhunleth** [comment]
That sounds good to me!
