### ISSUE TITLE
Add unit tests for emails

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#333]
**Describe the bug**

NervesHub sends out emails in a few places. None of those emails are unit tested.

**Expected behavior**

We have test coverage on emails too.

From @jlmcgehee21: It's pretty easy to add with Bamboo: https://hexdocs.pm/bamboo/readme.html#testing

**Comment by jjcarstens** [comment]
This seems to be done now with https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_www/test/nerves_hub_www/accounts/email_test.exs

Is there more to be completed here?
