### ISSUE TITLE
Store more metadata on CA Certificates

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#349]
**Describe the bug**

Here's a listing of my CA certificates:

```
$ mix nerves_hub.ca_certificate list --org fhunleth
NervesHub server: api.nerves-hub.org:443
NervesHub organization: fhunleth
Local NervesHub user password: 

CA Certificates:
------------
  serial:     126236587848883701081127509202651601401
  validity:   2019-01-29 - 2020-01-29 UTC
------------
  serial:     154694503113903429621761652948733676793
  validity:   2018-12-17 - 2019-12-17 UTC
------------
  serial:     164666524619156014971463271775540920591
  validity:   2019-01-24 - 2020-01-24 UTC
------------
```

It would be so helpful in telling these apart if there were some more information attached to them. Maybe a description that defaults to the filename of the certificate or maybe a registration timestamp.

While this requires a `nerves_hub_cli` update to fix the situation that I'm showing above, I'm reporting the bug here, since I'm guessing that most of the work to implement this is in this project.

**To Reproduce**

Run `mix nerves_hub.ca_certificate register ...` a few times and then list the certs.

**Comment by mobileoverlord** [comment]
We already track creation timestamps on the database records that we can surface. We could add a description field.
