### ISSUE TITLE
Sort devices by identifier

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#350]
**Describe the bug**
In the device view, the device order seems to change every once in a while. I'm not sure what determines the order, but it would be nice if the devices were ordered by identifier.

**To Reproduce**
Add a few devices and then go to the device view on at nerves-hub.org. Keep reloading the page.

**Expected behavior**
The device order is deterministic. For my use, ordering by device identifier is the logical way to sort devices. I'm sure that there are other ways, but this would make it easy to find devices at a glance.

**Comment by mobileoverlord** [comment]
Fixed in master
