### ISSUE TITLE
Use commas to delimit tags everywhere

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#379]
**Describe the bug**
Whether of not tags are comma or space separated is ambiguous in a few places in the UI. The CLI uses commas. The web UI does use commas on input, but the input text doesn't tell you this. Tags are also listed with whitespace separation, so it's hard to tell whether there's a space in a tag or whether you have too tags.

**To Reproduce**
Look at device and firmware tags

**Expected behavior**
I propose:
1. Whenever tags are printed in the UI, use comma's to separate them (in the future, I'm definitely open to other ideas, but this seems like a quick fix before we make a UX pass over the entire web UI)
2. Don't allow whitespace in tags - the CLI currently rejects tags with internal whitespace too
3. Add a comment where tags are entered to say that they're comma delimited.

**Comment by jjcarstens** [comment]
When I was creating devices with the CLI it was not delimiting on comma. So I'l going to adjust the CLI as well to ensure that happens and also warn if spaces were included. Then this should be done

**Comment by jjcarstens** [comment]
Well, turns out it wasn't delimiting on comma because of nerves_hub_web (which I fixed to handle delimiting when type casting).

So...this is done 🎉
