### ISSUE TITLE
Initial Device HTTP Endpoint Implementation

### ISSUE THREAD

**Issue by paulstatezny** [nerves-hub/nerves_hub_web#38]
Acceptance Criteria:

- There is an API endpoint at `GET /firmware-update`
- When any of the following conditions are met, the endpoint returns a 401 error:
  - The `X-Client-Dn` header is missing.
  - The `X-Client-Dn` header is not in the format `CN=identifier`.
  - The `identifier` in the `X-Client-Dn` header is not the case-sensitive identifier of a device in the `devices` table.
- The endpoint checks whether the device is eligible for a firmware update.
- A device is eligible for a firmware update if a deployment is found where the following is true:
  - The device (in the database) and firmware match in both architecture and platform
  - The device's current_version matches each of the version_requirements of the deployment. (Via `Version.match?/3`)
  - The device has **all** tags specified in the deployment.
- Integration tests
- The endpoint returns the following structure:

```json
{
  "eligible_firmware_update": "http://example.com/path/to/firmware/1.0.1/file.fw"
}
```

(If not eligible for a firmware update, null is returned:)

```json
{
  "eligible_firmware_update": null
}
```

Notes:
- This implementation does not allow for different tenants to have devices with the same `identifier`. This is an acknowledged major problem with this first version; we'll need to address it before using the product.

**Comment by fhunleth** [comment]
We're currently going full steam down the Phoenix channels path to getting firmware updates, but this issue is still important since some devices would prefer to remain disconnected most of the time (e.g., devices connected over metered connections). I'm marking this as V2 since the current client work won't exercise this.

**Comment by jlmcgehee21** [comment]
I believe this is live now: https://github.com/nerves-hub/nerves_hub_web/pull/287
