### ISSUE TITLE
Associate devices with products and support transferring a device between products

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#380]
**Describe the bug**
Devices are currently associated with organizations. When you list devices you get everything in your organization, but since devices can't easily switch between products, it would be better if they were associated with products. This way, you don't have to worry about messing with a device in a product grouping that you're not in charge of. There still needs to be a way to reassign a device to a different org/product grouping, but that's a less frequent use case.

The current workaround for this issue is to create multiple organizations. This isn't good since organizations are billing/permissions groupings.

**Comment by jlmcgehee21** [comment]
We had this association, then we broke it in favor of treating the firmware metadata as the single source of truth.  It would be possible to filter devices based on the metadata (i.e. the product name reported by the firmware matches exactly the current product you are viewing in the web), and present them at a `product/devices` endpoint.

**Comment by jjcarstens** [comment]
The first half of this seems to be completed. Devices are scoped to products. Making new issue for the second part
