### ISSUE TITLE
Force users to log in again after being inactive

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#383]
The amount of damage that someone can do on NervesHub is pretty high so I propose that NervesHub automatically log people out if they leave a tab open for a long time. Obviously, it's annoying to log in repeatedly. Perhaps automatically logging out after 15 minutes of inactivity is a reasonable compromise.

**Comment by joshk** [comment]
I'm going to close this issue for now as it has become a bit stale.
