### ISSUE TITLE
Email all users of an organization when a user is added or removed

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#403]
Updates to organizational settings should notify all users of that organization as a precaution against accidental or malicious changes.

I expect there to be more places, but the intention for this issue to only apply to users being added to or removed from organizations.

**Comment by pcmarks** [comment]
For adding a user there are two routes and controller support:

`POST /invite  => AccountController.accept_invite()`
`POST /register => AccountController.create()`

However, there are no routes nor any controller support for removing a user. 

Should the creation of remove user routes and controllers be in a separate issue? If so, then this issue should be limited to adding a user - not removing one.

**Comment by fhunleth** [comment]
Take a look at `/orgs/:org_name/users/:username`. See https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_api/lib/nerves_hub_api_web/controllers/org_user_controller.ex.

At the commandline, you can run `mix nerves_hub.org user add|remove USERNAME` to exercise that endpoint. It would be nice to remove users from organizations from the web UI as well and I'd agree that that's a separate issue.

**Comment by pcmarks** [comment]
OK. I was focused on the UI interface and forgot about the API.

**Comment by jjcarstens** [comment]
This seems to have been implemented. I am getting notifications when new user joins org
