### ISSUE TITLE
Make NervesHub email format consistent

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#404]
Currently emails from NervesHub are pretty simple and lack some consistency. GitHub has a nice template for sending emails, so how about let's follow it:

```
Subject: [NervesHub] User <other username> added to <your organization>

Hey <username>!

<message example>
<username> recently added <other username> to the <your organization>. Visit https://nerves-hub.org/something/something for more information.
</message example>

<probably don't add this yet>
To see this and other security events for your account, visit https://nerves-hub.org/settings/security.
</probably don't add this yet>

If you run into problems, please contact support by visiting https://nerves-hub.org/contact.

Thanks,
Your friends at NervesHub
```

**Comment by pcmarks** [comment]
Just so I am interpreting things correctly. The following [function](https://github.com/nerves-hub/nerves_hub_web/blob/abd03509131527a991173c3633c4cc064e811ec7/apps/nerves_hub_www/lib/nerves_hub_www/accounts/email.ex#L27) from `NervesHubWWW.Accounts.Email` does **not** mean that a new Organization has been created, rather a new User has been added to an organization. In other words, the subject is incorrect. Right?
```
  def org_user_created(email, %Org{} = org) do
    new_email()
    |> from(@from)
    |> to(email)
    |> subject("New NervesHub Organization Added")
    |> put_layout({NervesHubWWWWeb.LayoutView, :email})
    |> render("org_user_created.html", org: org)
  end
```

**Comment by fhunleth** [comment]
Yes
