### ISSUE TITLE
Change timestamps to be UTC

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#410]
In working on #409 trying to display timestamps in the browsers timezone, I noticed we are only using `NaiveDateTime` in all the database records. So trying assert the timezone in the UI is kind of moot.

But also, we should probably store timestamps in the database as a `:utc_datetime` type and strictly adhere to UTC then do conversions where needed for displaying.

Thoughts?

**Comment by fhunleth** [comment]
It sounds like there are three issues:

1. Timestamps aren't stored in the database as `:utc_datetime` types
2. The current code is calling `NaiveDateTime` instead of `DateTime`
3. You want the UI to show timestamps in UTC in the browser?

I have no opinions on #1, but it sounds good.

For #2, when the server is only working with UTC, is there a difference between `DateTime` and `NaiveDateTime`?

Not sure on #3. Local times seem pretty nice in the UI. I'm not sure that this is a top priority for me. I assume that you want UTC everywhere so that LiveView doesn't need to query the browser's timezone?

**Comment by jjcarstens** [comment]
Sort of. #2 isn’t that the code is calling `NaiveDateTime`. It’s the fact that all time stamps are stored to the DB as type naive_datetime. So anytime it is read from the DB into a struct and passed around, it is naive without a timezone.

Then for #3, we’re already trying to display times in the browser according to local timezone. But it’s inaccurate because times stored on records are naive so all it really does is tack on the timezone (I.e MST) to the naive time which breaks comparison. Cause you and I could look at the same record and you’d see `11:20 EDT` and I’d see `11:20 MDT` which kind of messes things up when trying to view the last device check in time or cert expiration, etc.

Also, when the times get written it’s basically just writing the time according to the server inserting. Most the time they are UTC, so not a huge deal to write that naively. But in a distributed system, one node could be in a different time zone than another and therefore could insert records at the same “time”, but since it’s naively and their current times would look different, the records would be different naive times (in theory). So usually just easier to enforce utc at the DB level for accurate time comparisons later on, then you can get fancy with time zones later if you want

**Comment by fhunleth** [comment]
I sure that the intention has been that all timestamps on the server are UTC. A PR to make that explicit seems fine.

**Comment by joshk** [comment]
After diving deep into why Phoenix/Ecto use `datetime` and not `utc_datetime`, I don't think this change is really worth it.

If this is all about showing date times in the UI using the users timezone, this is possible with what we have right now and isn't really related to the `datatime` issue. 

Phoenix/Ecto uses UTC as its timezone for generating timestamps, so we know all timestamps on the server are UTC. 

What we should ideally do is format this in the UI using js, as we can fetch the locale and timezone of the browser. 

I'm going to close this issue for the time being.
