### ISSUE TITLE
Unreferenced firmware not being garbage collected

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#411]
**Describe the bug**
Old firmware images that aren't referenced by a deployment are not being garbage collected after months.

**Expected behavior**
Unreferenced firmware images eventually get garbage collected.

**Comment by mobileoverlord** [comment]
This was fixed in https://github.com/nerves-hub/nerves_hub_web/pull/447#issuecomment-485516343

**Comment by mobileoverlord** [comment]
The firmware ttl dates were set starting today. It will take up until the default ttl time (7 days) for the firmware to be deleted.
