### ISSUE TITLE
Support sorting devices based on the columns

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#416]
When you have a lot of devices, the device list gets pretty long. It would be really useful to be able to click on the column heads (I'm happy with other mechanisms) and sort them based on last connection time, tags, firmware version, online, etc.

**Comment by jjcarstens** [comment]
Just to tack onto this: Would we also want to separate `online` vs `offline` devices in different tabs? Or is that too much UI to go through to find

**Comment by fhunleth** [comment]
My preference is that the "last connection" and "online" columns get merged and that `online` (or more accurately, `connected`) gets sorted as most recent.

I also don't know how pagination fits into this and LiveView. The device list is already getting kind of long, but it seems to load quickly, so it's not that bad. I imagine that will change at some point.

However, I'd be happy with just sorting the current columns and I can add issues for the others to defer that work for later.

**Comment by fhunleth** [comment]
@jjcarstens Did you do some work on this already?

**Comment by jjcarstens** [comment]
Yes. I have a branch that’s pretty much complete. Was just pushing other things forward first
