### ISSUE TITLE
Activate/Un-activate Deployments

### ISSUE THREAD

**Issue by paulstatezny** [nerves-hub/nerves_hub_web#42]
(stub)

**Comment by mobileoverlord** [comment]
@jlmcgehee21 I think this is done?

**Comment by jlmcgehee21** [comment]
afk, but it's implemented in the back end and controller. Not sure if there's an element in the form.

**Comment by mobileoverlord** [comment]
Yup, the button is there and as a bonus it seems to work!
<img width="438" alt="screen shot 2018-07-30 at 17 08 36" src="https://user-images.githubusercontent.com/1391351/43423785-50393d4a-941b-11e8-84e4-26c497c0ff59.png">
