### ISSUE TITLE
Show device count, firmware size and usage stats

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#428]
When we start really enforcing organization limits, it would be good to have the current organization counts listed as well. The current location for this would be the organization settings page.

**Comment by jjcarstens** [comment]
The new UI refresh in #630 starts showing device count on an org.

The firmware size and usage stats still need to be implemented

**Comment by joshk** [comment]
I'm going to close this issue as it is a little stale.

We will look into tackling better Product dashboard in the near future, which will include some of this information.
