### ISSUE TITLE
Reboot action should be available when an update is pending

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#430]
https://github.com/nerves-hub/nerves_hub_web/blob/40f87d7986ec6f67f720f4f7a95e30950c0e1e73/apps/nerves_hub_www/lib/nerves_hub_www_web/templates/device/show.html.leex#L48

Currently the only way to dispatch a `reboot` is if the device is `online`. You can be `online`. If a device has an `update pending` it is still `online`.

**Comment by mobileoverlord** [comment]
We should probably allow anything except "offline".

**Comment by fhunleth** [comment]
I'm concerned about the meaning of `device_status`. If the states are `offline`, `online`, and `update_pending`, then I'd like to refactor it before fixing this issue. It sounds like we should have two fields: one for `connected`/`disconnected` and another for `update_pending`/`no update_pending`.

**Comment by jjcarstens** [comment]
I forgot to mention I tacked this fix in with https://github.com/nerves-hub/nerves_hub_web/pull/464.

I agree with Frank on the "status" of devices and that's gradually being fixed and addressed in other issues
