### ISSUE TITLE
Create user certs from the web UI

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#437]
User certificate creation is currently broken. See https://github.com/nerves-hub/nerves_hub_web/pull/435

This issue tracks adding user certificate creation back.

**Comment by fhunleth** [comment]
See https://github.com/nerves-hub/nerves_hub_web/issues/315 for a use case

**Comment by joshk** [comment]
@fhunleth @jjcarstens is there still a strong use case for adding this?

**Comment by jjcarstens** [comment]
No. User certs were replaced by tokens for API requests

**Comment by oestrich** [comment]
Also pretty sure I deleted all of user certs a year ago, haha

**Comment by joshk** [comment]
ahhhh, this is related to API requests!

closing this for the time being.
