### ISSUE TITLE
Wrong template file extension?

### ISSUE THREAD

**Issue by pcmarks** [nerves-hub/nerves_hub_web#451]
Compiling https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_www/lib/nerves_hub_www_web/templates/deployment/show.html.leex
  resulted in the warning: `variable "f" is unused (if the variable is not meant to be used, prefix it with an underscore)`.

Although not related to the warning, it appears that the file has the wrong extension: `.leex`

**Expected behavior**
The file should have the extension: `eex`

**Comment by jjcarstens** [comment]
Actually, that is the file extension used for `Phoenix.LiveView` and stands for `LiveEEx`:

See https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view.ex#L286-L297

So the extension is correct as that is a LiveView page now, but that unused variable could be fixed

**Comment by pcmarks** [comment]
TIL: new extension! Sorry about that.
