### ISSUE TITLE
Internal Server Error on creating account from invite

### ISSUE THREAD

**Issue by jfcloutier** [nerves-hub/nerves_hub_web#472]
When creating an account from an emailed invite, I cause an Internal Server Error if I do not enter an email address in the user name field in the registration page.

Note that the registration was nonetheless successful with my email address as user name.

**To Reproduce**
1. Get an email invite
2. Click on link in invite
3. Enter a non-email in the user name field (e.g. jfcloutier)
4. Enter a password in the password field
5. Press "Register" button

**Expected behavior**
I would expect the user name field to be pre-filled with the email address the invite was sent to (it should probably also be read-only)
I should only need to enter a password and press "Register"

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Chrome
 - Version 73.0.3683.86

**Comment by jjcarstens** [comment]
I can also see a resolution to this being partially related to https://github.com/nerves-hub/nerves_hub_web/issues/473
