### ISSUE TITLE
User name isn't in audit log when changing tags

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#481]
My username seems to appear in the audit log for everything else that I do. It seems like changing tags it falls back to ID?

<img width="430" alt="Screen Shot 2019-05-24 at 9 04 15 AM" src="https://user-images.githubusercontent.com/64669/58330069-15124a80-7e04-11e9-977b-595ce010bbba.png">

**Comment by supersimple** [comment]
<img width="484" alt="Screen Shot 2019-10-13 at 1 38 24 PM" src="https://user-images.githubusercontent.com/773380/66720807-c408f000-edbe-11e9-99ae-4373754bb70d.png">

@fhunleth I am unable to reproduce this locally or online. Is it still happening to you?

**Comment by fhunleth** [comment]
Hmm.. Thanks for the reminder. I don't think I've seen it in a while. I'll close.
