### ISSUE TITLE
Can't stop pinging in remote IEx console

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#482]
Toolshed's `ping` command keeps pinging until you press the Enter key or so it says. This works in a regular shell, but doesn't work in the remote console:

<img width="997" alt="Screen Shot 2019-05-24 at 9 16 02 AM" src="https://user-images.githubusercontent.com/64669/58330414-d29d3d80-7e04-11e9-9c5f-30082b67c4e9.png">

The blank lines above are me trying to press Enter.

**Comment by jjcarstens** [comment]
Fixed with https://github.com/nerves-hub/nerves_hub_web/pull/615 🙌
