### ISSUE TITLE
Improve web user interface

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#492]
Please see https://www.dropbox.com/sh/fcqjvw41ll1i4bi/AABGkp39lr6bMiCRgb_x5dGUa?dl=0 for rough drawings of the proposed screens.

If you have input on this, please join the conversation on the #nerves_hub slack channel on the Elixir Lang slack or contact me or Justin. We're trying to work out the major flow quickly.

For small things that don't affect the global flow, we would like to hear about those as well, but there will be a second chance as PRs come in when the updates happen.

**Comment by chazwatkins** [comment]
> Has anyone started working on issue 492?  If not, I'd like to give it a go.  Does anyone have an issue with using tailwindcss for the ui updates?
<sub>[View in Slack](https://elixir-lang.slack.com/archives/CANV3GCAV/p1571447571039400)</sub>

**Comment by fhunleth** [comment]
@chazwatkins Thanks for asking us and offering help!

@mobileoverlord What are your feelings on this issue? Some time has gone by since June 5th when this was first entered.

**Comment by fhunleth** [comment]
@chazwatkins Let's stick with Bootstrap for now.

**Comment by oantila** [comment]
This could be closed now.

**Comment by mobileoverlord** [comment]
🎉
