### ISSUE TITLE
Clicking "mark healthy" or "mark unhealthy" requires page refresh

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#498]
![rec](https://user-images.githubusercontent.com/21150830/59863900-8f1dec80-933a-11e9-87ad-8bf0f5f6267e.gif)

(the colors here are a weird issue with my gif capture software, not the site itself)

**Comment by jjcarstens** [comment]
Hmm. That’s odd. I wonder if it’s an issue with the LV session. Possibly just need to assign the newly changed device so that it forces those elements to update with the new changes. I’ll take a look a little later

**Comment by mobileoverlord** [comment]
This is fixed in production by: https://github.com/nerves-hub/nerves_hub_web/pull/501
