### ISSUE TITLE
Logging into a nerves-hub account with org names other than default gives 404

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#528]
**Describe the bug**
I have two orgs on my account, `farmbot-staging` and `farmbot-production`. When i log into NervesHub i am sent to an org called `farmbot` which doesn't exist.
![rec](https://user-images.githubusercontent.com/21150830/60283430-f816de80-98bd-11e9-94da-aeb8fcea9502.gif)

**Comment by mobileoverlord** [comment]
The problem here is that users should not be allowed to delete the org that is created with their same username. The issue was corrected by fixing the data
