### ISSUE TITLE
Progress bar for uploading .fw files

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#53]
**Current behavior:**
When you upload a .fw file, the browser acts like it is working, but it's hard to tell how far it's gotten.

**Expected behavior:**
There's a progress bar or some feedback that lets you know that things are happening.

**Steps to reproduce:**
Go to the firmware tab, browse and then upload a .fw file.

**Comment by joshk** [comment]
With our planned more to LiveView for all Web interactions, we will get this for free.

I'm going to close this issue for the time being.
