### ISSUE TITLE
Support vulnerability scanning of uploaded firmware images

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#537]
There are several open-source vulnerability scan packages. See [FACT](https://fkie-cad.github.io/FACT_core/) for a start. It would be interesting to scan `.fw` files for vulnerabilities and possibly also check for Nerves/Elixir-specific issues. This would need to be opt-in, but would be a nice-to-have service to alert people to risks.

**Comment by joshk** [comment]
I love this idea, but I also know that its a significant unit of work that I don't see us starting in the next 12-18 months.

I'm going to close this issue for the time being.
