### ISSUE TITLE
Binary diff updates

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#538]
When using NervesHub on metered connections, it would be really nice to be able to send down binary diff images instead of full .fw files. NervesHub has many of the pieces to enable this service and `fwup` only needs some additions to support binary diff primitives (see bsdiff paper).

Let's track work on this here.

**Comment by jjcarstens** [comment]
Frank wrote up more on this idea here:
https://1drv.ms/w/s!AvSR_rwx-5Heg-Fu1Wn4Y5QVaMdyeA

**Comment by oantila** [comment]
This can probably be closed now as per https://github.com/nerves-hub/nerves_hub_web/pull/627
