### ISSUE TITLE
Files for translation

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#552]
Now that the pieces for crowdin are in place, we can start adjust files in the app to use `gettext` to translate strings as needed.

Here is an initial list of files that need to be adjusted to use translations. (best effort scan over the library. There may be more to come)

## NervesHubWWW
- [ ] account/edit.html.eex
- [ ] account/invite.html.eex
- [ ] account/new.html.eex
- [ ] account_certificate/index.html.eex
- [ ] account_certificate/new.html.eex
- [ ] account_certificate/show.html.eex
- [ ] audit_log/_audit_log_feed.html.eex
- [ ] deployment/edit.html.eex
- [ ] deployment/index.html.eex
- [ ] deployment/new.html.eex
- [ ] deployment/select-firmware.html.eex
- [ ] deployment/show.html.leex
- [ ] device/console.html.leex
- [ ] device/edit.html.leex
- [ ] device/index.html.leex
- [ ] device/new.html.eex
- [ ] device/show.html.leex
- [ ] firmware/index.html.eex
- [ ] firmware/upload.html.eex
- [ ] home/index.html.eex
- [ ] layout/_footer.html.eex
- [ ] layout/_navigation.html.eex
- [ ] layout/_sidebar.html.eex
- [ ] layout/app.html.eex
- [ ] org/edit.html.eex
- [ ] org/form.html.eex
- [ ] org/invite.html.eex
- [ ] org/new.html.eex
- [ ] org_certificate/index.html.eex
- [ ] org_key/edit.html.eex
- [ ] org_key/form.html.eex
- [ ] org_key/index.html.eex
- [ ] org_key/new.html.eex
- [ ] org_key/show.html.eex
- [ ] org_user/index.html.eex
- [ ] password_reset/new.html.eex
- [ ] password_reset/new_password_form.html.eex
- [ ] policy/coc.html.md
- [ ] policy/privacy.html.md
- [ ] policy/tos.html.md
- [ ] product/index.html.eex
- [ ] product/new.html.eex
- [ ] product/show.html.eex
- [ ] session/new.html.eex
- [ ] sponsor/index.html.eex

## NervesHubWebCore
- [ ] forgot_password.html.eex
- [ ] layout.html.eex
- [ ] tell_org_user_added.html.eex
- [ ] invite.html.eex
- [ ] org_user_created.html.eex
- [ ] tell_org_user_removed.html.eex

**Comment by joshk** [comment]
Sorry @jjcarstens , I'm going to close this issue as this doesn't look to be a near term priority
