### ISSUE TITLE
Publish update version information to client devices

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#580]
It would be nice to be able for nerves hub devices to be able to log the version that they are updating too. This information could be put in the `update` payload of the channel connection and the HTTP version as well.

**Comment by jjcarstens** [comment]
Resolved in https://github.com/nerves-hub/nerves_hub_web/pull/732 with the `%UpdatePayload{}` struct that is form and sent to the device on updates
