### ISSUE TITLE
Add link to invite user in /settings/{org}/users

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#582]
Right now you can invite a user from `/settings/{org}/profile`, but not from `/settings/{org}/users`. Sometimes that can cause confusing since `users` is where many might look to first when trying to add a user to their org.

**Comment by supersimple** [comment]
![image](https://user-images.githubusercontent.com/773380/72749327-f624ad80-3b76-11ea-9f22-63123ce8fc68.png)

It looks like this was already completed

**Comment by jjcarstens** [comment]
Yep. Sure was. Thanks!
