### ISSUE TITLE
Document nerves_hub management API

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#65]
The idea here is to expose an API for CI servers and other systems to interact with the `nerves_hub` and be able to do the same things that humans can do via the web UI.

**Comment by danielspofford** [comment]
Has any more thought been put into this? Tempting to explore https://github.com/xerions/phoenix_swagger here.

**Comment by jjcarstens** [comment]
I think this is mostly handled with docs.nerves-hub.org.

For more specific documentation, we should have explicit requests in new issues
