### ISSUE TITLE
Allow different device index page sizes

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#650]
The device index page is now hard coded to 25.

It would be nice to allow options to increase that page size or to also display "all" if desired

**Comment by oliryde** [comment]
@jjcarstens Do you think a dropdown menu with some predefined values would make sense?

**Comment by jjcarstens** [comment]
Sure. With a dropdown I kind of imagine predefined values and a number field where I can specify a custom number as well.

**Comment by oliryde** [comment]
@jjcarstens Do you think it belongs with the filters or do you think it should be separate?

**Comment by jjcarstens** [comment]
I don't have a preference here. My initial reaction is separate.

**Comment by oliryde** [comment]
Does it make sense to do it like this?
![Peek 2020-10-07 20-15](https://user-images.githubusercontent.com/6782555/95371016-ea7e4000-08d9-11eb-9246-f68a8f678fa3.gif)
The real values should be larger of course and the buttons should probably be moved to the right.

**Comment by jjcarstens** [comment]
I would prob put it at the top since the length of devices is variable. If I wanted to change, I don't want to scroll

**Comment by oliryde** [comment]
Good point. It's not very helpful if it keeps moving.
I'm not sure how well this works. At least it's not moving anymore.
![Peek 2020-10-08 00-19](https://user-images.githubusercontent.com/6782555/95394404-b5cfb000-08fc-11eb-90f3-8e73c33c9639.gif)

**Comment by jjcarstens** [comment]
LGTM! @coryjewell @Mrjaco12 - Do you have opinions on design here?

**Comment by Mrjaco12** [comment]
I don't have any opinion on the design. What's proposed here seems fine to me. I'm pretty sure we created a `handle_event` for updating pagination options so this should be pretty straightforward to add.

**Comment by oliryde** [comment]
I noticed the [existing](https://github.com/nerves-hub/nerves_hub_web/blob/35a5a6dedb7cc93162bc7cfd00662eba70c92592/apps/nerves_hub_www/lib/nerves_hub_www_web/live/device_live/index.ex#L125) ```handle_event``` for updating pagination options uses underscore for the incoming parameter
```elixir
%{"page_size" => page_size}
```
Isn't it more correct correct to use dash?
```elixir
%{"page-size" => page_size}
```
If underscore is used the attribute has to look like this which seems wrong.
```html
<button phx-click="set-paginate-opts" phx-value-page_size="25">
  25
</button>
```
Seems like ```content_tag/1``` converts underscores to dashes
```elixir
iex> Phoenix.HTML.Tag.tag(:button, data: [phx_click: "set-paginate-opts", phx_value_page_size: 25], value: 25) |> Phoenix.HTML.safe_to_string
"<button data-phx-click=\"set-paginate-opts\" data-phx-value-page-size=\"25\" value=\"25\">"
```

**Comment by Mrjaco12** [comment]
I would say feel free to update the attribute in whichever way makes the most sense for the maintainers. I'm not sure if there's an established pattern for this project or not. I like your suggestion of converting to underscores.

**Comment by oliryde** [comment]
I appreciate all of your feedback.
I'll try to create an initial pull request tonight.

**Comment by jjcarstens** [comment]
🙌 🎉 So ready for this PR :shipit: 😉 Thanks @oliryde!
