### ISSUE TITLE
More device details on the Console page

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#664]
The console page of a device only has the console. I'm finding myself having several console open lately and jumping between each requires I look at the URL to tell which it is.

It would be nice if we had a little more info on the console page. Maybe even just keep the device details? Or the console button is a show/hide action on the LiveView device#show page? Or even show the device identifier in the page title (instead of just `NervesHub`)

I'm not picky here just that _something_ would be nice

**Comment by mbhole1857** [comment]
Can you please elaborate on the issue finding it difficult to understand

**Comment by jjcarstens** [comment]
Sure! sorry..

This is the current console page:
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/11321326/95367358-e8908e80-0891-11eb-9371-c2382cb79e3a.png">

It shows no details about what device it is for. I'd like to see the device identifier _somewhere_ on that page so its available for quick glance. Like the details for the device#show page (which looks like this ¬)

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/11321326/95367698-4ae98f00-0892-11eb-967a-dcb3d120cf0d.png">

`poser` is my device identifier. Id like to see that on the `Console` page as well. As a bonus, it could be added to the page title so that it shows up in the tab also. Right now this is all you see in the tab title¬

<img width="164" alt="image" src="https://user-images.githubusercontent.com/11321326/95367883-8dab6700-0892-11eb-8d98-2c6b759739e5.png">

**Comment by brianberlin** [comment]
@jjcarstens I've been wondering if the console doesn't deserve a different layout that would fix scrolling weirdness. Right now when you attempt to scroll up or down in the console you end up scrolling the page instead.

**Comment by fhunleth** [comment]
Yes, anything that fixes the scrolling weirdness is 👍 👍 👍  from me.

**Comment by jjcarstens** [comment]
🍺or ☕ from me to whoever fixes the console scrolling weirdness!!

**Comment by jjcarstens** [comment]
Completed with #666
