### ISSUE TITLE
Paging through activities makes page selector grow wider

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#671]
**Describe the bug**
The following pictures show it happening. I'm clicking on the `>>` button between each one:

![image](https://user-images.githubusercontent.com/64669/96040141-cf5e8380-0e37-11eb-9799-d0b0a3335c1a.png)
![image](https://user-images.githubusercontent.com/64669/96040162-d9808200-0e37-11eb-9693-10762a0f38a6.png)
![image](https://user-images.githubusercontent.com/64669/96040200-e43b1700-0e37-11eb-995d-f426091f5fb2.png)
...
![image](https://user-images.githubusercontent.com/64669/96040236-f321c980-0e37-11eb-9883-4c7111bdefcf.png)

**Comment by joshk** [comment]
@fhunleth I noticed that the "Latest Activity" area was moved to the bottom, is this still an issue?
