### ISSUE TITLE
Allow delta updates to be opt-in

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#674]
[Firmwares get labeled as "patchable" if they have a few fwup fields in their `fwup.conf`](https://github.com/nerves-hub/nerves_hub_web/blob/main/apps/nerves_hub_web_core/lib/nerves_hub_web_core/firmwares.ex#L439), but that's basically all it takes to opt-in to firmware patches. Past that, everything happens autonomously.

We prob should allow opt-in settings on the org/firmware/deployment/whatever so that firmware patches can be avoided if needed without a whole new firmware deployed just to change some fields in `fwup.conf`

**Comment by oantila** [comment]
I think a good place for the opt-in toggle would be under the org settings, e.g. nerves-hub.org/settings/org-name

**Comment by jjcarstens** [comment]
Met with @Mrjaco12 @fhunleth and @mobileoverlord on this and the consensus seemed to be that the `Product Settings` felt like a good place to put this. That will allow you to opt-in to patches on smaller product which are still part of the same organization.

And there currently is a product settings page (with no actually changeable settings 🤣 ) that seems like a good place to drop this in.

`https://www.nerves-hub.org/org/{org}/{produt}/edit`

<img width="821" alt="image" src="https://user-images.githubusercontent.com/11321326/96504574-179fec00-1212-11eb-89d6-ea5500264e14.png">
