### ISSUE TITLE
Timestamps on device activity logs

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#680]
**Describe the bug**
Currently the activity logs look like this:

![image](https://user-images.githubusercontent.com/64669/97749405-63318000-1ac5-11eb-8e5d-c59f6bf74be9.png)

For very recent activities, knowing that something happened seconds or minutes ago is convenient, but beyond that, it would be great if the timestamps were shown. This would make it possible to correlate NervesHub events to events going on elsewhere. For example, in the picture above, knowing the event was "1 day ago" is not super helpful.

**Comment by chazwatkins** [comment]
@fhunleth Is this format acceptable?

![image](https://user-images.githubusercontent.com/9411090/97753286-7f342200-1ac3-11eb-9d82-e10f06f6f33a.png)

**Comment by fhunleth** [comment]
Yeah, that looks really nice to me. Thanks!
