### ISSUE TITLE
Can't use the same firmware signing key in two organizations

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#687]
**Describe the bug**
Register a firmware signing key and then try to register the same one in another org. It fails with an error message that it already exists, but it's not obvious why when you're in a different org.

Why would you do this?
1. If you need to create multiple orgs to segregate products managed by different teams, you still might want to keep the same dev firmware signing keys so that it's less confusing which one you use for development.
2. You don't care about firmware signatures on a hobby device. While NervesHub forces signatures, it can be nice to ship around devices to others that they can hook up and update via NervesHub. It seems wrong to disable signatures entirely since we want to promote that as a best practice, but letting people use known firmware keys seems reasonable and then it's easy for them to swap them out when they want to lock down their device.

**Comment by jjcarstens** [comment]
Fixed with https://github.com/nerves-hub/nerves_hub_web/commit/893f8311d314da95961a283ff16b4c04380a9975
