### ISSUE TITLE
Console page shows devices as offline when they're online

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#689]
It looks like devices only show up as offline on the console page. I haven't see a device show up as online yet, so I suspect that the logic either isn't right or it changed since #666 was implemented. Here's a screenshot:

![image](https://user-images.githubusercontent.com/64669/98569156-eef29b80-227f-11eb-9b3d-44120a1de7c5.png)

This seems like it should be easy to reproduce, but if it turns out not to be, I'll try to get more details.

**Comment by brianberlin** [comment]
Whoops, I copied over the template and didn't think about subscribing to the device updates. I started on a fix for this yesterday but i'm not really sure how to verify that it all works in my local environment. I'll put up a PR a little later.

**Comment by fhunleth** [comment]
@brianberlin We're discussing removing everything off the console page on Slack to fix the scrolling issue and provide more screen real estate. While I previously really wanted the fix to this, I'm feeling like if you don't have it ready yet, then perhaps we should figure out what we want before putting more time into this.
