### ISSUE TITLE
Deleting a device from the web works, but goes to the wrong view

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#699]
**Describe the bug**
Delete a device from the web UI. The web UI reports an error and takes you to the NervesHub home page. It does look like the device is deleted, though.

**To Reproduce**

1. Create a device on a product (in any way)
2. Log into the web UI
3. Find the device and delete it

**Comment by brianberlin** [comment]
@fhunleth i wasn't able to reproduce this issue. I found something that was maybe introduced with 4e6ab4b and resolved by 9c7e1fb but nothing in recent commits. think maybe it's stale now.

**Comment by jjcarstens** [comment]
Fixed with #769
