### ISSUE TITLE
Update project to use Bootstrap 4

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#72]

**Comment by fhunleth** [comment]
@paulstatezny I'm assigning to you only since Nate isn't in our org yet and he wanted to ask you some questions on how to get the template over here.

**Comment by jlmcgehee21** [comment]
Bootstrap4 is in place via a CDN link in the layout view in :point_up: PR.  Should still probably be properly added to the assets. @stwf

**Comment by mobileoverlord** [comment]
This is in master
