### ISSUE TITLE
show identifier on Device show like console

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#723]
While debugging multiple devices it would be nice to have the title of the tab show the device identifier
![Screenshot from 2021-02-03 11-22-27](https://user-images.githubusercontent.com/21150830/106797963-2ae49500-6612-11eb-8c86-eae2956aaeed.png)

**Comment by fhunleth** [comment]
OMG, I so need this too and I didn't realize how much until you pointed it out!
