### ISSUE TITLE
Suggestion to use Oban.Plugins.Pruner

### ISSUE THREAD

**Issue by pojiro** [nerves-hub/nerves_hub_web#776]
Currently rows of oban_jobs table increases monotonically, so I suggest to use [Oban.Plugins.Pruner](https://hexdocs.pm/oban/Oban.Plugins.Pruner.html).

This plugin does

> Periodically delete completed, cancelled and discarded jobs based on age.

I can make a simple PR for this, but before that I would like to ask the development team what the duration of the max_age option should be.

**Comment by joshk** [comment]
I agree, this would be a great addition.

I think a max age of 7 days is a good default, and then having it be configurable in `runtime.exs`

Would you be interested in adding this?
