### ISSUE TITLE
Support expired Signer certificates?

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#778]
Right now if you have a Signer certificate that is expired, we reject any new device connection that's certificate was generated with that signer (see [here](https://github.com/nerves-hub/nerves_hub_web/blob/main/apps/nerves_hub_device/lib/nerves_hub_device/ssl.ex#L112-L113) and [here](https://github.com/nerves-hub/nerves_hub_web/blob/main/apps/nerves_hub_device/lib/nerves_hub_device/ssl.ex#L129-L132))

It seems AWS will allow the expired signer cert to add devices if the signer was already registered and trusted. Is that a feature we should match and make configurable on the Signer CA for the org?

**Comment by dnrce** [comment]
Is this the same as #838?

**Comment by jjcarstens** [comment]
No, this is for new device certificate registration.

Say we have the signer, and the device is registered (with no certs). The first device connection will only register its cert if the signer CA is not expired
