### ISSUE TITLE
Create branch for code that deploys to nerves-hub.org

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#790]
Since nerves-hub.org is in the process of being shut down (see [post](https://elixirforum.com/t/action-advised-nerveshub-sunset/42925)) and development moved to private forks, this repository has looked inactive. Part of this is that the `main` branch is hooked into CI to deploy to nerves-hub.org, and we don't want to accidentally mess it up in this transition.

How about:

1. Create a `nerves-hub.org` branch that has the current code and CI integration
2. Remove the CI integration with nerves-hub.org in `main`.
3. Start moving fixes and new features from private branches to `main`

**Comment by mobileoverlord** [comment]
To clarify, the `main` branch does not automatically deploy to the servers at `nerves-hub.org`, there is an [approval step](https://github.com/nerves-hub/nerves_hub_web/blob/main/.circleci/config.yml#L479-L484) that is pressed to deploy a commit point on main to those servers as well as a separate approval step for deploying to staging for integration testing.

**Comment by fhunleth** [comment]
Right, the purpose of this change is to avoid any PRs from being deployed on nerves-hub.org. We could also do it the other way and have a `next` branch.
