### ISSUE TITLE
Add support for a data retention policy on the logs

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#795]
Currently clearing old data from the audit logs requires manual intervention. It would be nice to have a UI option to set the number of days logs should be retained and have a cron job clear out old entries. A per-org setting would suffice.

**Comment by joshk** [comment]
I was hoping this could be a Product setting, but looking into the Audit Log schema and how Audit Logs are linked to Orgs, it might make more sense to have this be an Org setting, at least for now.
