### ISSUE TITLE
CA server should be optional

### ISSUE THREAD

**Issue by dnrce** [nerves-hub/nerves_hub_web#848]
Since a8edab4e73e6251a0a8940f16320d01913b012e8, a CA server is no longer necessary for any functionality. However, one is currently still required in order to bring up nerves_hub_web. It should be possible to configure nerves_hub_web without pointing it to a CA server.

**Comment by jjcarstens** [comment]
We've actually been planning to remove the use of a CA server entirely, but I guess we should get consensus first to make sure a configurable CA server is not desirable.

Do you have any strong opinions either way?

**Comment by dnrce** [comment]
We've only ever used it for API user auth, so as far as my own case is concerned, it's wholly unnecessary now.

**Comment by dnrce** [comment]
I would assume that getting rid of the CA server would also allow the PKI arrangement to be simplified a bit.

**Comment by joshk** [comment]
@jjcarstens can this be closed?
