### ISSUE TITLE
Propose to have new library like `nerves_hub_certificate`

### ISSUE THREAD

**Issue by pojiro** [nerves-hub/nerves_hub_web#850]
I made sample PR #849 to fix #753.

In this work, I think we may need a library like `nerves_hub_certificate`, cause certs are used on the both client and server sides. If this library can be created, important common certification logic can be consolidated in one place. 
This explanation may not be enough to convey what I have in mind, so I made sample PR.

There is already a certs logic in [nerves_hub_cli](https://github.com/nerves-hub/nerves_hub_cli/blob/main/lib/nerves_hub_cli/certificate.ex), client side, and if we plant to quit using nerves_hub_ca, wouldn't we need a certs logic in nerves_hub_web, server side?

**Comment by joshk** [comment]
@jjcarstens can you weigh in on this?

**Comment by joshk** [comment]
With the sample PR being closed, I think it might be best to close this issue for the time being.

I agree that we don't want duplicate code in multiple places, and yet more libs can have their own downsides.

**Comment by pojiro** [comment]
@joshk 

> I agree that we don't want duplicate code in multiple places, and yet more libs can have their own downsides.

Thank you for handling this. I agree with you.
