### ISSUE TITLE
Web frontend can't connect to websocket, with terraform deployment

### ISSUE THREAD

**Issue by jeanparpaillon** [nerves-hub/nerves_hub_web#851]
**Describe the bug**

When deploying our own instance of NervesHub, following instructions from  https://docs.nerves-hub.org/nerves-hub/custom-deployment/requirements , the frontend won't connect to nerves_hub_ww websocket, because of wrong origin.

I think the issue could be solved by allowing a custom `NervesHubWWW.Endpoint, check_origin` option, though env var.

If you think this is the right way to proceed, I can provide PR.

**Comment by tonnenpinguin** [comment]
Hey!
We are running a setup based on the terraform deployment as well without any issues. Are you sure you set the correct `domain` in the `terraform.tfvars` file? I don't think you should require a custom check_origin option for same host access

**Comment by jeanparpaillon** [comment]
Thank you for your feedback. Sorry, the error came from a small modification on domain name. My bad.

**Comment by tonnenpinguin** [comment]
Glad you found your issue :)
