### ISSUE TITLE
Firmware upload signature verification

### ISSUE THREAD

**Issue by mattlorey** [nerves-hub/nerves_hub_web#88]
When a firmware file is uploaded, we verify the firmware is valid and then check if it is signed, and if so, match the verify the signature with they key(s) on the tenant.

The way we determine a firmware is signed is no longer valid - update to use `fwup`'s programmatic interface

**Comment by mobileoverlord** [comment]
@mattlorey I believe this is in master, can we close this?

**Comment by mattlorey** [comment]
Yeah it was done in https://github.com/nerves-hub/nerves_hub_web/pull/90
