### ISSUE TITLE
Let users create device certs via the UI

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#93]
There are a few ways of creating certificates for devices. This issue covers having a screen that lets users enter in a name or ID for a device and then having the server generate (with the help of `nerves_hub_ca`) a device certificate. The user would then download the certificate and keys and would install them on the device. I think that this is part of the device creation page, but if another part of the UI makes more sense, it could be there too. We will eventually want to allow users to create certificates for devices as a separate step to creating/registering the device with Nerves Hub. However, that separation could be done as part of another issue if it is involved.

**Comment by joshk** [comment]
With the advent of Shared Secrets auth, `nerves_hub_ca` no longer under active development, and the recommendations to use Trust and Go crypto chips, I'm going to close this issue for the time being.
