### ISSUE TITLE
mix ecto.reset finishes with an {:error, #Ecto.Changeset}

### ISSUE THREAD

**Issue by ivanhercaz** [nerves-hub/nerves_hub_web#930]
**Describe the bug**
I am testing NervesHub 2.0 and I am really shocked! Really good job, thank you! I tested it locally, but now I am going to test in a server.

But before I want to submit this "bug" that doesn't produce errors when executing NervesHub, but maybe it helps to debug.

When I did `mix ecto.reset` everything goes fine until it finishes with `{:error, #Ecto.Changeset}`. The stacktrace:

```
** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :i
, 15, 126>>, der: <<48, 130, 1, 213, 48, 130, 1, 123, 160, 3, 2, 1, 2, 2, 21, 0, 183, 
134, 72, 206, ...>>, fingerprint: "3017332607368673A2EF0E2B1BF832A61A653F5E", not_afte
BC469CF599AC529CA76F33BD35118265C372", serial: "10456136957141869122544633197622963806
5, 114>>}, errors: [public_key_fingerprint: {"public key already associated with anoth
    (nerves_hub_www 0.1.0) test/support/fixtures.ex:324: NervesHub.Fixtures.device_cer
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    priv/repo/seeds.exs:59: NervesHub.SeedHelpers.nerves_team_seed/1
    (elixir 1.14.0) lib/code.ex:1245: Code.require_file/2
    (mix 1.14.0) lib/mix/tasks/run.ex:144: Mix.Tasks.Run.run/5
    (mix 1.14.0) lib/mix/tasks/run.ex:84: Mix.Tasks.Run.run/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.0) lib/mix/task.ex:479: Mix.Task.run_alias/6
    (mix 1.14.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

**To Reproduce**
1. Run `mix ecto.reset on a new NervesHub instance.

**Expected behavior**
Finishes the creation of the database without errors.

**Desktop (please complete the following information):**
 - OS: Linux - Manjaro

**Comment by oestrich** [comment]
Ah yeah, I keep forgetting to actually commit that. You can only create one cert with how this is set up right now for the seeds. Gotta get rid of that line and seeds will work. If you pull main again this should be fixed. Thanks for reporting!

**Comment by ivanhercaz** [comment]
Nice! Really happy to help reporting issues.
Again, thank you for your awesome work with NervesHub!
