### ISSUE TITLE
(Protocol.UndefinedError) protocol Enumerable not implemented for #Ecto.Association.NotLoaded<association :products is not loaded>

### ISSUE THREAD

**Issue by ivanhercaz** [nerves-hub/nerves_hub_web#935]
**Describe the bug**
"My Organizations" section returns `Protocon.UndefinedError` when you try to access.

Error shown in the browser:
```
Protocol.UndefinedError at GET /account/nerveshub/organizations
protocol Enumerable not implemented for #Ecto.Association.NotLoaded<association :products is not loaded> of type Ecto.Association.NotLoaded (a struct)
```

Stacktrace in IEx log:
```
[error] #PID<0.2038.0> running NervesHubWeb.Endpoint (connection #PID<0.2026.0>, stream id 3) terminated
Server: nerveshub.<domain>.tech:4000 (http)
Request: GET /account/nerveshub/organizations
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for #Ecto.Association.NotLoaded<association :products is not loaded> of type Ecto.Association.NotLoaded (a struct)
        (elixir 1.13.2) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.13.2) lib/enum.ex:143: Enumerable.reduce/3
        (elixir 1.13.2) lib/enum.ex:4144: Enum.reduce/3
        (nerves_hub_www 0.1.0) lib/nerves_hub_web/templates/layout/_navigation.html.heex:28: anonymous fn/3 in NervesHubWeb.LayoutView."_navigation.html"/1
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/engine.ex:124: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/engine.ex:83: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/engine.ex:88: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/engine.ex:79: anonymous fn/3 in Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/1
        (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/engine.ex:79: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/1
        (phoenix_live_view 0.16.4) lib/phoenix_live_view/engine.ex:140: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3
        (phoenix 1.6.16) lib/phoenix/controller.ex:772: Phoenix.Controller.render_and_send/4
        (nerves_hub_www 0.1.0) lib/nerves_hub_web/controllers/org_controller.ex:1: NervesHubWeb.OrgController.action/2
        (nerves_hub_www 0.1.0) lib/nerves_hub_web/controllers/org_controller.ex:1: NervesHubWeb.OrgController.phoenix_controller_pipeline/2
        (phoenix 1.6.16) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
        (nerves_hub_www 0.1.0) lib/nerves_hub_web/endpoint.ex:1: NervesHubWeb.Endpoint.plug_builder_call/2
        (nerves_hub_www 0.1.0) lib/plug/debugger.ex:136: NervesHubWeb.Endpoint."call (overridable 3)"/2
        (nerves_hub_www 0.1.0) lib/nerves_hub_web/endpoint.ex:1: NervesHubWeb.Endpoint."call (overridable 4)"/2
        (nerves_hub_www 0.1.0) lib/spandex_phoenix.ex:151: NervesHubWeb.Endpoint.call/2
        (phoenix 1.6.16) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
```

**To Reproduce**
1. Go to user menu.
2. Click on "Settings"
3. Click on "My Organizations"

**Expected behavior**
Expect to see my organizations section.

**Desktop (please complete the following information):**
 - OS: Linux (Manjaro)
 - Browser: Ungoogled Chromium
 - Version: 111.0.5563.146 (Official Build, ungoogled-chromium) Arch Linux (64 bits) 

**Additional context**
I am testing NervesHub in a Hetzner Cloud server with `dev` environment, although I am having some problems with the certificates (I can't get https working on `:4000` and if I visit `:4001` to see what returns the log in IEx, I get:
```
[notice] TLS :server: In state :hello at tls_record.erl:539 generated SERVER ALERT: Fatal - Unexpected Message
 - {:unsupported_record_type, 71}
```

Could it be related? It may not be a bug, just a bad configuration of the certificates by my side.

**Comment by oestrich** [comment]
Thanks, for the report! This is fixed on main now by https://github.com/nerves-hub/nerves_hub_web/commit/386e3b152a4d92969bfd1548edce920c88b309ec

This page was forgotten when I added the My Organizations page to be the homepage and display product counts.

The issue you're seeing around TLS is 4001 is the device endpoint which requires client authentication so going there otherwise will look weird. The web side of NervesHub doesn't host its own TLS any more and expects something in front of it to handle that, like Caddy/nginx/etc. The self hosting PR should handle this with Caddy.

**Comment by ivanhercaz** [comment]
@oestrich, you are awesome! You don't let my incidents live more than a day haha. Really happy to help reporting issues.

> The issue you're seeing around TLS is 4001 is the device endpoint which requires client authentication so going there otherwise will look weird.

All right, so it is because it is not intended to be visited with the browser. I am going to check if it works with the certificates configuration I am using to replace the one available on the fixture directory, for that I am going to try to connect one of my devices.

> The web side of NervesHub doesn't host its own TLS any more and expects something in front of it to handle that, like Caddy/nginx/etc. The self hosting PR should handle this with Caddy.

Awesome! Thank you very much for all this information. So instead of set up a reverse nginx-proxy with Let's Encrypt and all of this stuff, I am going to wait for the self hosting PR.
