### ISSUE TITLE
Feedback issues with the self hosting

### ISSUE THREAD

**Issue by ivanhercaz** [nerves-hub/nerves_hub_web#952]
Hi!
First of all, awesome work! Thanks to all the team, specially to @oestrich, because after #932 it is easier to deploy NervesHub and I am very grateful that now there isn't a dependency with AWS, service that keeps optional. Of course, before the PR it was possible to deploy on other hosting services, but there were necessary more tweaks.

Then, about this issue, if you consider it should be separated in different specific issues, just tell me! I also don't filled the bug report issue template because I don't know if these can be considered bugs.

I followed the "Self Hosting" setup instructions and I experienced some issues, and experiencing that issues I also find a possible workaround at least for my case.

**`ExecStart` systemd service issue**

`systemd: nerves_hub.service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.`

This happened with "Starting NervesHub". When I checked the `nerves_hub.service` file I find it with the sections duplicated, this two times in the same file:
```
[Unit]
Description=NervesHub
After=network.target
 
[Service]
User=root
Group=root
WorkingDirectory=/home/root/nerves_hub/current
Environment=LANG=en_US.UTF-8
EnvironmentFile=/etc/nerves_hub.env
ExecStart=/home/root/nerves_hub/current/bin/nerves_hub start
SyslogIdentifier=nerves_hub
RemainAfterExit=no
Restart=on-failure
RestartSec=5
 
[Install]
WantedBy=multi-user.target 
```

So my intuition says that maybe removing the duplicated one and reloading the daemon could solve this issue, but this still returned me the same error. Looking for a solution in internet, I find this answer on [Unix StackExchange](https://unix.stackexchange.com/a/500267/172992), in which it is suggested to add an `ExecStart` (empty) before the "true"  `ExecStart`:

```
[Service]
ExecStart=  
ExecStart=/home/root/nerves_hub/current/bin/nerves_hub start
SyslogIdentifier=nerves_hub
RemainAfterExit=no
Restart=on-failure
RestartSec=5
```

Then I did `systemctl daemon-reload` and this problems was solved.

**`current_path` in `./bin/remote deploy`**

Then I had to fight a bit with the paths set in `./bin/remote`, specifically in the `deploy` command, because the user I used doesn't enter directly in its user directory in `/home`, so as a fast workaround I edited the paths that produces me the problem. This produces problems exporting the environment variables of `/etc/nerves_hub.env`, but finally it has an easy solution/workaround.

I think it may be interesting to include or suggest to include `RemoteCommand cd /home/%user%` in `remote_host` file. I have not tested it yet (if I do it, I will report it here).

Well, now I am dealing with the connection of my testing Nerves device with my NervesHub, so maybe soon I will post a thread of doubts/issues I am having trying to link the device with the hub using NervesHubLink, hehe.

**Comment by jjcarstens** [comment]
Thanks @ivanhercaz !

The deployment script is really a "courtesy best effort starting point" that is focused on being a generic, yet typical helper.

The issues you're describing seem fairly setup specific and if you're able to identify the specific problems and how to harden the script for it, then a PR would be most appreciated 😉 otherwise I'd suggest maintaining your own version of the script you know works for your setup

Outside of that, I'd love to keep varying deployment discussions in the Elixir Forum where they are more long lived and discoverable. The problem of deploying a web server is not unique to NervesHub so I'm sure many others with experience can help provide insight as well
